[package]
name = "wasm-worker-example"
version = "0.1.0"
authors = ["amiller68 <alex@banyan.computer>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "^0.2"
cfg-if = "^0.1"
console_error_panic_hook = { version = "^0.1", optional = true }
wee_alloc = { version = "^0.4", optional = true }
js-sys = "^0.3"
wasm-bindgen-futures = "^0.4"
wasm-streams = "^0.3"
futures = "^0.3"
sha2 = "^0.10"
serde-wasm-bindgen = "^0.6"
hex = "^0.4"

[dependencies.web-sys]
version = "^0.3"
features = [
  "File",
  "Blob",
  "ReadableStream",
]

[dependencies.gloo]
version = "^0.10"
features = [
  "console",
  "worker"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
