const path = require('path');

const CopyPlugin = require('copy-webpack-plugin')
const WasmPackPlugin = require('@wasm-tool/wasm-pack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin')

const indexConfig = {
  mode: "development",
  entry: {
    index: "./www/index.ts",
  },
  plugins: [
    new CopyPlugin({
      patterns: [{ from: "./www/index.html", to: "./index.html" }],
    }),
    new CircularDependencyPlugin({
      // `onStart` is called before the cycle detection starts
      onStart({ compilation }) {
        console.log('start detecting webpack modules cycles');
      },
      // `onDetected` is called for each module that is cyclical
      onDetected({ module: webpackModuleRecord, paths, compilation }) {
        // `paths` will be an Array of the relative module paths that make up the cycle
        // `module` will be the module record generated by webpack that caused the cycle
        compilation.errors.push(new Error(paths.join(' -> ')))
      },
      // `onEnd` is called before the cycle detection ends
      onEnd({ compilation }) {
        console.log('end detecting webpack modules cycles');
      },
    })
  ],

  experiments: {
    asyncWebAssembly: true,
  },

  resolve: {
    extensions: [".js", ".ts", ".tsx"],
    modules: [
      path.resolve(__dirname, "./www"),
      path.resolve(__dirname, "./node_modules"),
    ],
  },

  devServer: {
    hot: "only",
    port: 8000,
    allowedHosts: "all",
    headers: {
      "Cross-Origin-Embedder-Policy": "require-corp",
      "Cross-Origin-Opener-Policy": "same-origin"
    }
  },

  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "ts-loader",
        },
      },
    ],
  },

  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "index.js",
  },
};

const workerConfig = {
  mode: "development",
  entry: {
    index: "./www/worker.ts",
  },
  plugins: [
    new WasmPackPlugin({
      crateDirectory: __dirname,
      extraArgs: "--target web",
    })
  ],

  experiments: {
    asyncWebAssembly: true,
  },

  resolve: {
    extensions: [".js", ".ts", ".tsx"],
    modules: [
      path.resolve(__dirname, "./www"),
      path.resolve(__dirname, "./node_modules"),
    ],
  },

  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "ts-loader",
        },
      },
    ],
  },

  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "worker.js",
  },

  target: "webworker",
};

module.exports = (_env) => {
  return [
    indexConfig,
    workerConfig
  ]
}